unit FileRipperExtensions;

interface

uses
  Windows; // only for DWORD

const
///////////////////////////////////////
/// Format Extension
  FORMAT_EXTENSION_NONE = 'NONE';
  FORMAT_EXTENSION_WAV  = 'WAV';
  FORMAT_EXTENSION_OGG  = 'OGG';
  FORMAT_EXTENSION_RIFF = 'RIFF';
  FORMAT_EXTENSION_IFF =  'IFF';
  FORMAT_EXTENSION_AVI  = 'AVI';
  FORMAT_EXTENSION_BIK  = 'BIK';

  FORMAT_EXTENSION_JFIF = 'JPG';
  FORMAT_EXTENSION_DDS  = 'DDS';
  FORMAT_EXTENSION_PNG  = 'PNG';
  FORMAT_EXTENSION_TGA  = 'TGA';
  FORMAT_EXTENSION_BMP  = 'BMP';
  FORMAT_EXTENSION_ZLIB = 'ZLIB';
  FORMAT_EXTENSION_APE  = 'APE';
  FORMAT_EXTENSION_M4A  = 'M4A';
  FORMAT_EXTENSION_MP4  = 'MP4';
  FORMAT_EXTENSION_MOV  = 'MOV';
  FORMAT_EXTENSION_7ZIP = '7ZIP';
  FORMAT_EXTENSION_ZIP  = 'ZIP';
  FORMAT_EXTENSION_AIFF = 'AIFF';
  FORMAT_EXTENSION_MIDI = 'MIDI';
  FORMAT_EXTENSION_PSD  = 'PSD';
  FORMAT_EXTENSION_MP3  = 'MP3';
  FORMAT_EXTENSION_SWF  = 'SWF';
  FORMAT_EXTENSION_GIF  = 'GIF';
  FORMAT_EXTENSION_EXE  = 'EXE';
  FORMAT_EXTENSION_DLL  = 'DLL';
  FORMAT_EXTENSION_3GP  = '3GP';
  FORMAT_EXTENSION_3G2  = '3G2';
  FORMAT_EXTENSION_SWS  = 'SWS';
  FORMAT_EXTENSION_SIFF = 'SIFF';
  FORMAT_EXTENSION_FLV  = 'FLV';
  FORMAT_EXTENSION_RMF  = 'RMF';
  FORMAT_EXTENSION_ASF  = 'ASF';
  FORMAT_EXTENSION_SND  = 'SND';
  FORMAT_EXTENSION_3DS  = '3DS';
  FORMAT_EXTENSION_WVPK = 'WVPK';
  FORMAT_EXTENSION_RAF  = 'RAF';
  FORMAT_EXTENSION_SMK  = 'SMK';

  FORMAT_EXTENSION_XPR0 = 'XPR';
  FORMAT_EXTENSION_XPR2 = 'XPR';
  FORMAT_EXTENSION_XMV  = 'XMV';
  FORMAT_EXTENSION_TTF  = 'TTF';
  FORMAT_EXTENSION_XWMA = 'XWMA';
  FORMAT_EXTENSION_CAB  = 'CAB';
  FORMAT_EXTENSION_XNB  = 'XNB';
  FORMAT_EXTENSION_WAD2 = 'WAD2';
  FORMAT_EXTENSION_MDL7 = 'MDL7';
  FORMAT_EXTENSION_4XM  = '4XM';
  FORMAT_EXTENSION_PSMF = 'PSMF';
  FORMAT_EXTENSION_FLI  = 'FLI';
  FORMAT_EXTENSION_FLC  = 'FLC';
  FORMAT_EXTENSION_FLX  = 'FLX';
  FORMAT_EXTENSION_TTA  = 'TTA';
  FORMAT_EXTENSION_OFR  = 'OFR';
  FORMAT_EXTENSION_LA   = 'LA';
  FORMAT_EXTENSION_LPAC = 'LPAC';
  FORMAT_EXTENSION_VQF  = 'VQF';
  FORMAT_EXTENSION_AVS  = 'AVS';
  FORMAT_EXTENSION_NSV  = 'NSV';
  FORMAT_EXTENSION_PVA  = 'PVA';
  FORMAT_EXTENSION_BRES = 'BRES';
  FORMAT_EXTENSION_REFT = 'REFT';
  FORMAT_EXTENSION_RFNA = 'RFNA';
  FORMAT_EXTENSION_RFNT = 'RFNT';
  FORMAT_EXTENSION_RSAR = 'RSAR';
  FORMAT_EXTENSION_RSTM = 'RSTM';
  FORMAT_EXTENSION_GR2  = 'GR2';
  FORMAT_EXTENSION_LWO2 = 'LWO2';
  FORMAT_EXTENSION_SDAT = 'SDAT';
  FORMAT_EXTENSION_SSEQ = 'SSEQ';
  FORMAT_EXTENSION_SSAR = 'SSAR';
  FORMAT_EXTENSION_SWAR = 'SWAR';
  FORMAT_EXTENSION_SBNK = 'SBNK';
  FORMAT_EXTENSION_NCER = 'NCER';
  FORMAT_EXTENSION_NANR = 'NANR';
  FORMAT_EXTENSION_NCLR = 'NCLR';
  FORMAT_EXTENSION_NARC = 'NARC';
  FORMAT_EXTENSION_8SVX = '8SVX';
  FORMAT_EXTENSION_DMSC = 'DMSC';
  FORMAT_EXTENSION_DMSG = 'DMSG';
  FORMAT_EXTENSION_THP  = 'THP';
  FORMAT_EXTENSION_FILM = 'FILM';

  FORMAT_EXTENSION_RAS  = 'RAS';
  FORMAT_EXTENSION_DPX1 = 'DPX1';
  FORMAT_EXTENSION_DPX4 = 'DPX4';
  FORMAT_EXTENSION_R3D  = 'R3D';

  FORMAT_EXTENSION_XBG2  = 'XBG2';
  FORMAT_EXTENSION_XBG3  = 'XBG3';
  FORMAT_EXTENSION_XBG4  = 'XBG4';
  FORMAT_EXTENSION_XBG5  = 'XBG5';
  FORMAT_EXTENSION_XBG6  = 'XBG6';
  FORMAT_EXTENSION_XBG7  = 'XBG7';


///
///////////////////////////////////////

implementation

end.
